### ISSUE TITLE
real AB/12 button position

### ISSUE THREAD

**Issue by soundsnow** [williehwc/wonderdroid-x#50] opened 2022-10-12 07:18 UTC
![image104](https://user-images.githubusercontent.com/109885044/195278652-dd6f9141-c087-415d-954c-5faac3650962.png)
![image105](https://user-images.githubusercontent.com/109885044/195278658-e65110ae-be12-4a59-be1d-b18249891381.png)
![image106](https://user-images.githubusercontent.com/109885044/195278664-0b2e789a-77f1-4297-aa2b-58681832f2f7.png)

**Comment by williehwc** [comment] 2022-10-15 14:34
You can change the A+B position in the Preferences > Size and position... > A+B position.
Duplicate of #35. Please do not post duplicate issues.

**Closed by williehwc** 2022-10-15 14:34 UTC
